myapp/song_posts/forms.py
from platform import release
from wsgiref.validate import validator
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class FavSongsForm(FlaskForm):
  title = StringField('Title', validators=[DataRequired()])
  musician = StringField('Musician', validators=[DataRequired()])
  genre = StringField('Genre', validators=[DataRequired()])
  releaseyear = StringField('Release Year', validators=[DataRequired()])
  text = TextAreaField('Comments', validators=[DataRequired()])

  submit = SubmitField('Post')

myapp/song_posts/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint, abort
from flask_login import current_user, login_required
from myapp import db 
from myapp.models import FavSongs
from myapp.song_posts.forms import FavSongsForm

song_posts = Blueprint('song_posts', __name__)

@song_posts.route('/create', methods=['GET', 'POST'])
@login_required
def create_post():
  form = FavSongsForm()
  if form.validate_on_submit():
    song_post = FavSongs(title=form.title.data, musician=form.musician.data, genre=form.genre.data, releaseyear=form.releaseyear.data, text=form.text.data, user_id=current_user.id)
    db.session.add(song_post)
    db.session.commit()
    flash('Song Post Created')
    print('Song Post was Created')
    return redirect(url_for('core.index'))
  return render_template('create_post.html', form=form)


@song_posts.route('/<int:song_post_id>')
def song_post(song_post_id):
  song_post = FavSongs.query.get_or_404(song_post_id)
  return render_template('song_post.html', title=song_post.title, date=song_post.date, post=song_post)


@song_posts.route('/<int:song_post_id>/update',methods=['GET','POST'])
@login_required
def update(song_post_id):
    song_post = FavSongs.query.get_or_404(song_post_id)

    if song_post.author != current_user:
        abort(403)

    form = FavSongsForm()

    if form.validate_on_submit():
        song_post.title = form.title.data
        song_post.musician = form.musician.data
        song_post.genre = form.genre.data
        song_post.releaseyear = form.releaseyear.data
        song_post.text = form.text.data
        db.session.commit()
        flash('Song Post Updated')
        return redirect(url_for('song_posts.song_post',song_post_id=song_post.id))

    elif request.method == 'GET':
        form.title.data = song_post.title
        form.musician.data = song_post.musician
        form.genre.data = song_post.genre
        form.releaseyear.data = song_post.releaseyear
        form.text.data = song_post.text

    return render_template('create_post.html',title='Updating',form=form)


@song_posts.route('/<int:song_post_id>/delete',methods=['GET','POST'])
@login_required
def delete_post(song_post_id):

    song_post = FavSongs.query.get_or_404(song_post_id)
    if song_post.author != current_user:
        abort(403)

    db.session.delete(song_post)
    db.session.commit()
    flash('Song Post Deleted')
    return redirect(url_for('core.index'))

myapp/users/views.py
from crypt import methods
from operator import methodcaller
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from myapp import db
from myapp.models import User, FavSongs
from myapp.users.forms import RegistrationForm, LoginForm, UpdateUserForm

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, username=form.username.data, password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for Registration!')
        return redirect(url_for('users.login'))
    
    return render_template('register.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('Log in Success!')

            next = request.args.get('next')

            if next ==None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html',form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit(): 
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User account updated!!')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    return render_template('account.html', form=form)

@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    song_posts = FavSongs.query.filter_by(author=user).order_by(FavSongs.date.desc()).paginate(page=page, per_page=5) 
    return render_template('user_song_posts.html', song_posts=song_posts, user=user)

myapp/templates/account.html
{% extends "base.html" %}
{% block content %}
   
<div class="jumbotron">
    <div align="center">
        <h1>Account deatils for {{current_user.username}}</h1>
    </div>
</div>

<div class="container">
    <form method="POST" action="" enctype="multipart/form-data">
        <div class="form-group">
            {{form.hidden_tag()}}
        </div>
        <div class="form-group">
            {{form.username.label(class='form-group')}} 
            {{form.username(class='form-control')}}
        </div>
        <div class="form-group">
            {{form.email.label(class='form-group')}} 
            {{form.email(class='form-control')}}
        </div>
      
        <div class="form-group">
            {{form.submit(class='btn btn-primary')}}
        </div>
       
       
    </form>
</div>
{% endblock %}

myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" size=32x32 href="{{ url_for('static', filename='images/Favicon.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bangers&display=swap" rel="stylesheet">
    <title>What Song?</title>
</head>
<body>
    <ul class="nav">
        <li class="nav-link" class="nav-left">
            <a href="{{url_for('core.index')}}">Home</a>
        </li>

        {% if current_user.is_authenticated %}
        <li class="nav-link" class="nav-left">
            <a href="{{url_for('song_posts.create_post')}}">Add Recommendation</a> 
        </li>
        <li class="nav-link" class="nav-right">
            <a href="{{url_for('users.account')}}">Account</a>
        </li>
        <li class="nav-link" class="nav-right">
            <a href="{{url_for('users.logout')}}">Log Out</a>
        </li>
        {% else %}
        <li class="nav-link" class="nav-right">
            <a href="{{url_for('users.login')}}">Log In</a>
        </li>
        <li class="nav-link" class="nav-right">
            <a href="{{url_for('users.register')}}">Register</a>
        </li>
        {% endif %}
    </ul>

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

myapp/templates/create_post.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
      <form class="form-group" method="POST">
          {{form.hidden_tag()}}

          <div class="form-group">
              {{form.title.label(class="form-control-label")}}
              {{form.title(class="form-control form-control-lg")}}
          </div>
          <div class="form-group">
            {{form.musician.label(class="form-control-label")}}
            {{form.musician(class="form-control form-control-lg")}}
          </div>
          <div class="form-group">
            {{form.genre.label(class="form-control-label")}}
            {{form.genre(class="form-control form-control-lg")}}
          </div>
          <div class="form-group">
            {{form.releaseyear.label(class="form-control-label")}}
            {{form.releaseyear(class="form-control form-control-lg")}}
          </div>
          <div class="form-group">
            {{form.text.label(class="form-control-label")}}
            {{form.text(class="form-control form-control-lg")}}
          </div>
          <div class="form-group">
            {{form.submit(class="btn btn-outline-info")}}
          </div>
      </form>
    </div>
{% endblock %}

myapp/templates/index.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1 class="index-header">Discover New Music</h1>
    </div>
    <div class="container">
        {% for post in song_posts.items %}
            <div class="card">
                <div class="car-boy">
                    <h4>{{ post.title }}</h4>
                    <h4>Musician: {{post.musician}}</h4>
                    <h4>Recommended by: {{post.author.username}}</h4>
                    <a class="btn btn-primary" href="{{url_for('song_posts.song_post', song_post_id=post.id)}}">Details</a>
                </div>
            </div>
        {% endfor %}
    </div>

    <nav aria-label="Page Navigation example">
        <ul class="pagination justify-content-center">
            {% for page_num in song_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if song_posts.page == page_num %}
                <li class="page-item disabled">
                    <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{ page_num }}</a>
                </li>
                {% endif %}
            {% endfor %}
        </ul>
    </nav>
{% endblock %}

myapp/templates/login.html
{% extends "base.html" %}
{% block content %}
   
<form method="POST">
    {{form.hidden_tag()}}
    {{form.email.label}}{{form.email}}<br>
    {{form.password.label}}{{form.password}}<br>
    {{form.submit()}}

</form>
{% endblock %}

myapp/templates/register.html
{% extends "base.html" %}
{% block content %}
   
<form method="POST">
    {{form.hidden_tag()}}
    {{form.email.label}}{{form.email}}<br>
    {{form.username.label}}{{form.username}}<br>
    {{form.password.label}}{{form.password}}<br>
    {{form.pass_confirm.label}}{{form.pass_confirm}}<br>
    {{form.submit()}}
</form>
{% endblock %}

myapp/templates/song_post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Details Page</h1>
  <h2>Title: {{ post.title }}</h2>
  <h2>Musician: {{post.musician}}</h2>
  <h2>Genre: {{post.genre}}</h2>
  <h2>Release Year: {{post.releaseyear}}</h2>
  <h2>Comments: {{post.text}}</h2>
  <h5>Recommended by: {{post.author.username}}</h5>
  <h5>Published: {{ post.date.strftime('%B %d, %Y') }}</h5>
   {% if post.author == current_user %}
     <div>
       <a class="btn btn-secondary" href="{{ url_for('song_posts.update', song_post_id=post.id) }}">Update</a>
       <br>
       <form action="{{ url_for('song_posts.delete_post', song_post_id=post.id) }}" method="POST">
        <input class="btn btn-danger" type="submit" value="Delete">
      </form>
     </div>
   {% endif %}
</div>
{% endblock content %}

myapp/templates/user_song_posts.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="jumbotron">
            <div align="center">
                <h1>Welcome to the page for {{user.username}}</h1>
            </div>
        </div>
     {% for post in song_posts.items %}
    <h2>
        <a href="{{url_for('song_posts.song_post', song_post_id=post.id)}}">{{post.title}}</a>
    </h2>
    Written By: <a href="{{url_for('users.user_posts', username=post.author.username)}}">{{post.author.username}}</a>

    <p class="text-muted">
        Published On: {{post.date.strftime("%y-%m-%d")}}
    </p>
    <br>
    <p>{{post.text}}</p>
    <br>
    {% endfor %}
    </div>

    <nav aria-label="Page Navigation example">
        <ul class="pagination justify-content-center">

            {% for page_num in song_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if song_posts.page == page_num %}
                <li class="page-item disabled">
                    <a class="page-link" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{ page_num }}</a>
                </li>
                {% endif %}
            {% endfor %}
        </ul>
    </nav>


{% endblock %}